baseline_bank:
	# Extracting a problem for SVN
	./baseline_bank.py romipdata bank_train_noname baseline_bank.prob
	# Extracting testing data
	./baseline_bank.py romipdata bank_test_etalon_noname baseline_bank.test
